-- CRAVA V9 — Store, configurable boxes, orders, points, referrals and ratings
-- Run this entire file once in Supabase SQL Editor.
-- It is written to upgrade the old V8 database safely and can also be used on a fresh project.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) Core profile and legacy collection tables
-- =========================================================

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Member',
  member_number bigint generated by default as identity unique,
  phone_e164 text,
  points integer not null default 0 check(points >= 0),
  xp integer not null default 0 check(xp >= 0),
  box_count integer not null default 0 check(box_count >= 0),
  referral_code text,
  referred_by uuid references public.profiles(id),
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists phone_e164 text;
alter table public.profiles add column if not exists points integer not null default 0;
alter table public.profiles add column if not exists referral_code text;
alter table public.profiles add column if not exists referred_by uuid references public.profiles(id);
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create unique index if not exists profiles_referral_code_uidx
  on public.profiles(upper(referral_code))
  where referral_code is not null;

create table if not exists public.boxes(
  id uuid primary key default gen_random_uuid(),
  box_number integer unique not null check(box_number > 0),
  claim_code_hash text not null,
  status text not null default 'not_released' check(status in('not_released','active','claimed')),
  rarity text not null default 'standard' check(rarity in('standard','golden','rare')),
  order_id uuid,
  activated_at timestamptz,
  claimed_at timestamptz,
  claimed_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.boxes add column if not exists order_id uuid;

create table if not exists public.user_badges(
  user_id uuid references auth.users(id) on delete cascade,
  badge_key text not null,
  earned_at timestamptz not null default now(),
  primary key(user_id,badge_key)
);

-- Keep the old V8 ratings table for compatibility. New order ratings use order_ratings below.
create table if not exists public.ratings(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  box_id uuid not null references public.boxes(id) on delete cascade,
  product_id text not null,
  rating integer not null check(rating between 1 and 5),
  note text,
  created_at timestamptz not null default now(),
  unique(box_id,product_id)
);

-- =========================================================
-- 2) Store catalogue
-- =========================================================

create table if not exists public.box_sizes(
  code text primary key check(code in('S','M','L','XL')),
  name_ar text not null,
  name_en text not null,
  cookie_count integer not null check(cookie_count between 1 and 20),
  roll_count integer not null check(roll_count between 1 and 20),
  people_count integer not null check(people_count between 1 and 20),
  price numeric(10,3) not null check(price >= 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.flavor_options(
  code text primary key,
  item_type text not null check(item_type in('cookie','roll')),
  category_name text not null,
  name_ar text not null,
  name_en text not null,
  description_ar text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.delivery_areas(
  id bigint generated by default as identity primary key,
  name_ar text unique not null,
  delivery_fee numeric(10,3) not null check(delivery_fee >= 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.box_sizes(code,name_ar,name_en,cookie_count,roll_count,people_count,price,is_active,sort_order) values
  ('S','CRAVA S','CRAVA S',3,3,3,6.000,true,10),
  ('M','CRAVA M','CRAVA M',4,4,4,8.000,true,20),
  ('L','CRAVA L','CRAVA L',5,5,5,10.000,true,30),
  ('XL','CRAVA XL','CRAVA XL',6,6,6,12.000,true,40)
on conflict(code) do update set
  name_ar=excluded.name_ar,
  name_en=excluded.name_en,
  cookie_count=excluded.cookie_count,
  roll_count=excluded.roll_count,
  people_count=excluded.people_count,
  sort_order=excluded.sort_order;

insert into public.flavor_options(code,item_type,category_name,name_ar,name_en,description_ar,is_active,sort_order) values
  ('noir_kinder','cookie','Noir','Noir Kinder','Noir Kinder','كوكيز كاكاو بحشوة كندر',true,10),
  ('noir_nutella','cookie','Noir','Noir Nutella','Noir Nutella','كوكيز كاكاو بحشوة نوتيلا',true,20),
  ('amber_kinder','cookie','Amber','Amber Kinder','Amber Kinder','كوكيز ذهبي بحشوة كندر',true,30),
  ('amber_nutella','cookie','Amber','Amber Nutella','Amber Nutella','كوكيز ذهبي بحشوة نوتيلا',true,40),
  ('twist_chocolate','roll','Twist','🍫 Twist – Chocolate','Twist – Chocolate','رول مقرمش بالشوكولاتة',true,50),
  ('twist_strawberry','roll','Twist','🍓 Twist – Strawberry','Twist – Strawberry','رول مقرمش بالفراولة',true,60),
  ('twist_custard','roll','Twist','🍮 Twist – Custard','Twist – Custard','رول مقرمش بالكاسترد',true,70),
  ('twist_lotus','roll','Twist','🍪 Twist – Lotus','Twist – Lotus','رول مقرمش باللوتس',true,80)
on conflict(code) do update set
  item_type=excluded.item_type,
  category_name=excluded.category_name,
  name_ar=excluded.name_ar,
  name_en=excluded.name_en,
  description_ar=excluded.description_ar,
  sort_order=excluded.sort_order;

insert into public.delivery_areas(name_ar,delivery_fee,is_active,sort_order) values
  ('جبل النصر',2.000,true,10),
  ('النصر',2.000,true,15),
  ('الهاشمي',2.000,true,18),
  ('الهاشمي الشمالي',2.000,true,20),
  ('الهاشمي الجنوبي',2.000,true,30),
  ('القويسمة',2.000,true,40),
  ('ماركا',2.000,true,48),
  ('ماركا الشمالية',2.000,true,50),
  ('ماركا الجنوبية',2.000,true,60),
  ('الأشرفية',2.000,true,70),
  ('المحطة',2.000,true,80),
  ('جبل التاج',2.000,true,90),
  ('جبل النزهة',2.000,true,100),
  ('النزهة',2.000,true,105),
  ('ضاحية الأمير حسن',2.000,true,110),
  ('طبربور',2.000,true,120),
  ('عبدون',3.000,true,200),
  ('أبو نصير',3.000,true,210),
  ('الجبيهة',3.000,true,220),
  ('الجاردنز',3.000,true,230),
  ('الشميساني',3.000,true,240),
  ('الصويفية',3.000,true,250),
  ('تلاع العلي',3.000,true,260),
  ('خلدا',3.000,true,270),
  ('دابوق',3.000,true,280),
  ('شفا بدران',3.000,true,290),
  ('مرج الحمام',3.000,true,300),
  ('وسط البلد',3.000,true,310),
  ('جبل عمان',3.000,true,320),
  ('جبل الحسين',3.000,true,330),
  ('رأس العين',3.000,true,340),
  ('الوحدات',3.000,true,350),
  ('المقابلين',3.000,true,360),
  ('أم أذينة',3.000,true,370),
  ('الرابية',3.000,true,380),
  ('البيادر',3.000,true,390),
  ('وادي السير',3.000,true,400),
  ('ضاحية الرشيد',3.000,true,410),
  ('صويلح',3.000,true,420),
  ('أم السماق',3.000,true,430),
  ('المدينة الرياضية',3.000,true,440),
  ('عرجان',3.000,true,450),
  ('اليادودة',3.000,true,460),
  ('أبو علندا',3.000,true,470),
  ('خريبة السوق',3.000,true,480)
on conflict(name_ar) do update set
  delivery_fee=excluded.delivery_fee,
  is_active=excluded.is_active,
  sort_order=excluded.sort_order;

-- =========================================================
-- 3) Orders, structured selections, points, referrals, ratings
-- =========================================================

create table if not exists public.orders(
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  customer_name text not null,
  phone_e164 text not null,
  area text not null,
  street text not null,
  building text not null,
  floor text,
  apartment text,
  order_notes text,
  box_size_code text references public.box_sizes(code),
  box_name text,
  box_price numeric(10,3) not null default 0,
  subtotal numeric(10,3) not null default 0,
  delivery_fee numeric(10,3) not null default 0,
  points_used integer not null default 0 check(points_used between 0 and 100),
  points_discount numeric(10,3) not null default 0,
  total numeric(10,3) not null default 0,
  points_balance_after integer,
  referral_code text,
  referrer_id uuid references auth.users(id),
  referral_rewarded_at timestamptz,
  points_refunded_at timestamptz,
  payment_method text not null default 'cash_on_delivery' check(payment_method='cash_on_delivery'),
  status text not null default 'new' check(status in('new','confirmed','preparing','out_for_delivery','delivered','cancelled')),
  admin_note text,
  delivered_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade an older orders table if it already exists.
alter table public.orders add column if not exists order_notes text;
alter table public.orders add column if not exists box_size_code text references public.box_sizes(code);
alter table public.orders add column if not exists box_name text;
alter table public.orders add column if not exists box_price numeric(10,3) not null default 0;
alter table public.orders add column if not exists subtotal numeric(10,3) not null default 0;
alter table public.orders add column if not exists delivery_fee numeric(10,3) not null default 0;
alter table public.orders add column if not exists points_used integer not null default 0;
alter table public.orders add column if not exists points_discount numeric(10,3) not null default 0;
alter table public.orders add column if not exists total numeric(10,3) not null default 0;
alter table public.orders add column if not exists points_balance_after integer;
alter table public.orders add column if not exists referral_code text;
alter table public.orders add column if not exists referrer_id uuid references auth.users(id);
alter table public.orders add column if not exists referral_rewarded_at timestamptz;
alter table public.orders add column if not exists points_refunded_at timestamptz;
alter table public.orders add column if not exists payment_method text not null default 'cash_on_delivery';
alter table public.orders add column if not exists admin_note text;
alter table public.orders add column if not exists delivered_at timestamptz;
alter table public.orders add column if not exists cancelled_at timestamptz;
alter table public.orders add column if not exists updated_at timestamptz not null default now();

create table if not exists public.order_items(
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  item_type text not null check(item_type in('cookie','roll','candy','legacy')),
  position integer not null default 1,
  option_code text,
  option_name text not null,
  category_name text,
  quantity integer not null default 1 check(quantity > 0),
  unit_price numeric(10,3) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.order_items add column if not exists item_type text not null default 'legacy';
alter table public.order_items add column if not exists position integer not null default 1;
alter table public.order_items add column if not exists option_code text;
alter table public.order_items add column if not exists option_name text;
alter table public.order_items add column if not exists category_name text;
alter table public.order_items add column if not exists quantity integer not null default 1;
alter table public.order_items add column if not exists unit_price numeric(10,3) not null default 0;
alter table public.order_items add column if not exists created_at timestamptz not null default now();

-- Compatibility with an older order_items schema that used generic products.
do $$
begin
  if exists(
    select 1 from information_schema.columns
    where table_schema='public' and table_name='order_items' and column_name='product_name'
  ) then
    execute 'alter table public.order_items alter column product_name drop not null';
    execute 'update public.order_items set option_name=coalesce(option_name,product_name) where option_name is null';
  end if;
  if exists(
    select 1 from information_schema.columns
    where table_schema='public' and table_name='order_items' and column_name='product_id'
  ) then
    execute 'alter table public.order_items alter column product_id drop not null';
  end if;
end $$;

-- Add the optional physical-box/order relationship after both tables exist.
do $$
begin
  if not exists(select 1 from pg_constraint where conname='boxes_order_id_fkey') then
    alter table public.boxes
      add constraint boxes_order_id_fkey foreign key(order_id) references public.orders(id) on delete set null;
  end if;
end $$;

create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists orders_user_created_idx on public.orders(user_id,created_at desc);
create index if not exists orders_status_created_idx on public.orders(status,created_at desc);

create table if not exists public.points_ledger(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id uuid references public.orders(id) on delete set null,
  points integer not null,
  reason text not null,
  transaction_key text unique,
  created_at timestamptz not null default now()
);

create index if not exists points_ledger_user_idx on public.points_ledger(user_id,created_at desc);

create table if not exists public.referrals(
  id uuid primary key default gen_random_uuid(),
  inviter_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null unique references auth.users(id) on delete cascade,
  referral_code text not null,
  qualifying_order_id uuid unique references public.orders(id) on delete set null,
  reward_xp integer not null default 100,
  reward_status text not null default 'pending' check(reward_status in('pending','rewarded','cancelled')),
  rewarded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(inviter_id <> referred_user_id)
);

create index if not exists referrals_inviter_idx on public.referrals(inviter_id,created_at desc);

create table if not exists public.order_ratings(
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  box_rating integer not null check(box_rating between 1 and 5),
  delivery_rating integer not null check(delivery_rating between 1 and 5),
  comment text check(char_length(coalesce(comment,'')) <= 1000),
  created_at timestamptz not null default now()
);

create index if not exists order_ratings_created_idx on public.order_ratings(created_at desc);

-- =========================================================
-- 4) Helpers and account trigger
-- =========================================================

create or replace function public.normalize_jordan_phone(p_phone text)
returns text
language plpgsql
immutable
as $$
declare
  v text := regexp_replace(coalesce(p_phone,''),'[^0-9+]','','g');
begin
  if v ~ '^07[0-9]{8}$' then
    return '+962' || substr(v,2);
  elsif v ~ '^\+9627[0-9]{8}$' then
    return v;
  elsif v ~ '^9627[0-9]{8}$' then
    return '+' || v;
  end if;
  return null;
end $$;

create or replace function public.new_referral_code()
returns text
language plpgsql
volatile
security definer
set search_path=public
as $$
declare
  v text;
begin
  loop
    v := 'CRV' || upper(substr(encode(gen_random_bytes(5),'hex'),1,7));
    exit when not exists(select 1 from public.profiles where upper(referral_code)=v);
  end loop;
  return v;
end $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,display_name,referral_code)
  values(
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'),''),'Member'),
    public.new_referral_code()
  )
  on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Fill referral codes for old accounts.
do $$
declare r record;
begin
  for r in select id from public.profiles where referral_code is null loop
    update public.profiles set referral_code=public.new_referral_code() where id=r.id;
  end loop;
end $$;

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce((select is_admin from public.profiles where id=auth.uid()),false)
$$;

-- =========================================================
-- 5) Customer functions
-- =========================================================

create or replace function public.create_crava_order(
  p_customer_name text,
  p_phone text,
  p_area text,
  p_street text,
  p_building text,
  p_floor text default null,
  p_apartment text default null,
  p_order_notes text default null,
  p_box_size_code text default null,
  p_cookie_selections jsonb default '[]'::jsonb,
  p_roll_selections jsonb default '[]'::jsonb,
  p_points_to_use integer default 0,
  p_referral_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_user uuid := auth.uid();
  v_profile public.profiles;
  v_size public.box_sizes;
  v_area public.delivery_areas;
  v_phone text;
  v_order public.orders;
  v_code text;
  v_option public.flavor_options;
  v_pos integer;
  v_points integer := coalesce(p_points_to_use,0);
  v_discount numeric(10,3);
  v_total numeric(10,3);
  v_referrer public.profiles;
  v_existing_ref public.referrals;
  v_ref_code text := upper(trim(coalesce(p_referral_code,'')));
begin
  if v_user is null then
    raise exception 'SIGN IN REQUIRED';
  end if;

  select * into v_profile from public.profiles where id=v_user for update;
  if not found then
    raise exception 'PROFILE NOT FOUND';
  end if;

  if char_length(trim(coalesce(p_customer_name,''))) < 2 then
    raise exception 'INVALID CUSTOMER NAME';
  end if;

  v_phone := public.normalize_jordan_phone(p_phone);
  if v_phone is null then
    raise exception 'INVALID JORDAN PHONE';
  end if;

  if char_length(trim(coalesce(p_street,''))) < 2 or char_length(trim(coalesce(p_building,''))) < 1 then
    raise exception 'INCOMPLETE ADDRESS';
  end if;

  select * into v_area
  from public.delivery_areas
  where is_active=true and name_ar=trim(coalesce(p_area,''));
  if not found then
    raise exception 'DELIVERY OUTSIDE AMMAN';
  end if;

  select * into v_size
  from public.box_sizes
  where code=upper(trim(coalesce(p_box_size_code,''))) and is_active=true;
  if not found then
    raise exception 'INVALID BOX SIZE';
  end if;

  if jsonb_typeof(p_cookie_selections) <> 'array'
     or jsonb_array_length(p_cookie_selections) <> v_size.cookie_count then
    raise exception 'COOKIE SELECTIONS INCOMPLETE';
  end if;

  if jsonb_typeof(p_roll_selections) <> 'array'
     or jsonb_array_length(p_roll_selections) <> v_size.roll_count then
    raise exception 'ROLL SELECTIONS INCOMPLETE';
  end if;

  -- Validate all selected option codes before creating anything.
  for v_code in select jsonb_array_elements_text(p_cookie_selections) loop
    if not exists(select 1 from public.flavor_options where code=v_code and item_type='cookie' and is_active=true) then
      raise exception 'INVALID COOKIE OPTION';
    end if;
  end loop;

  for v_code in select jsonb_array_elements_text(p_roll_selections) loop
    if not exists(select 1 from public.flavor_options where code=v_code and item_type='roll' and is_active=true) then
      raise exception 'INVALID ROLL OPTION';
    end if;
  end loop;

  if v_points < 0 or v_points > 100 then
    raise exception 'POINTS LIMIT IS 100';
  end if;
  if v_points > v_profile.points then
    raise exception 'INSUFFICIENT POINTS';
  end if;

  v_discount := round((v_points::numeric / 100.0),3);
  v_total := greatest(round(v_size.price + v_area.delivery_fee - v_discount,3),0);

  if v_ref_code <> '' then
    select * into v_referrer
    from public.profiles
    where upper(referral_code)=v_ref_code;

    if not found then
      raise exception 'INVALID REFERRAL CODE';
    end if;
    if v_referrer.id=v_user then
      raise exception 'CANNOT USE OWN REFERRAL CODE';
    end if;

    select * into v_existing_ref
    from public.referrals
    where referred_user_id=v_user
    for update;

    if found and v_existing_ref.reward_status='rewarded' then
      raise exception 'REFERRAL ALREADY USED';
    elsif found and v_existing_ref.inviter_id<>v_referrer.id then
      raise exception 'REFERRAL ALREADY REGISTERED';
    end if;
  end if;

  insert into public.orders(
    user_id,customer_name,phone_e164,area,street,building,floor,apartment,order_notes,
    box_size_code,box_name,box_price,subtotal,delivery_fee,points_used,points_discount,total,
    points_balance_after,referral_code,referrer_id,payment_method,status
  ) values(
    v_user,trim(p_customer_name),v_phone,v_area.name_ar,trim(p_street),trim(p_building),
    nullif(trim(coalesce(p_floor,'')),''),nullif(trim(coalesce(p_apartment,'')),''),
    nullif(trim(coalesce(p_order_notes,'')),''),v_size.code,v_size.name_ar,v_size.price,
    v_size.price,v_area.delivery_fee,v_points,v_discount,v_total,v_profile.points-v_points,
    nullif(v_ref_code,''),case when v_ref_code='' then null else v_referrer.id end,
    'cash_on_delivery','new'
  ) returning * into v_order;

  v_pos := 0;
  for v_code in select jsonb_array_elements_text(p_cookie_selections) loop
    v_pos := v_pos + 1;
    select * into v_option from public.flavor_options where code=v_code;
    insert into public.order_items(order_id,item_type,position,option_code,option_name,category_name,quantity,unit_price)
    values(v_order.id,'cookie',v_pos,v_option.code,v_option.name_ar,v_option.category_name,1,0);
  end loop;

  v_pos := 0;
  for v_code in select jsonb_array_elements_text(p_roll_selections) loop
    v_pos := v_pos + 1;
    select * into v_option from public.flavor_options where code=v_code;
    insert into public.order_items(order_id,item_type,position,option_code,option_name,category_name,quantity,unit_price)
    values(v_order.id,'roll',v_pos,v_option.code,v_option.name_ar,v_option.category_name,1,0);
  end loop;

  insert into public.order_items(order_id,item_type,position,option_code,option_name,category_name,quantity,unit_price)
  values(v_order.id,'candy',1,'orbs','Orbs','Candy',1,0);

  if v_points > 0 then
    update public.profiles
    set points=points-v_points,
        phone_e164=v_phone,
        display_name=trim(p_customer_name),
        updated_at=now()
    where id=v_user;

    insert into public.points_ledger(user_id,order_id,points,reason,transaction_key)
    values(v_user,v_order.id,-v_points,'استخدام نقاط في الطلب #' || lpad(v_order.order_number::text,6,'0'),'order-use-' || v_order.id::text);
  else
    update public.profiles
    set phone_e164=v_phone,
        display_name=trim(p_customer_name),
        updated_at=now()
    where id=v_user;
  end if;

  if v_ref_code <> '' then
    insert into public.referrals(inviter_id,referred_user_id,referral_code,qualifying_order_id,reward_status)
    values(v_referrer.id,v_user,v_ref_code,v_order.id,'pending')
    on conflict(referred_user_id) do update set
      qualifying_order_id=excluded.qualifying_order_id,
      referral_code=excluded.referral_code,
      inviter_id=excluded.inviter_id,
      reward_status='pending',
      updated_at=now()
    where public.referrals.reward_status<>'rewarded';

    update public.profiles set referred_by=v_referrer.id,updated_at=now()
    where id=v_user and referred_by is null;
  end if;

  return jsonb_build_object(
    'ok',true,
    'order_id',v_order.id,
    'order_number',v_order.order_number,
    'subtotal',v_order.subtotal,
    'delivery_fee',v_order.delivery_fee,
    'points_used',v_order.points_used,
    'points_discount',v_order.points_discount,
    'total',v_order.total,
    'points_balance_after',v_order.points_balance_after
  );
end $$;

create or replace function public.submit_order_rating(
  p_order_id uuid,
  p_box_rating integer,
  p_delivery_rating integer,
  p_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders;
  v_rating public.order_ratings;
begin
  if auth.uid() is null then raise exception 'SIGN IN REQUIRED'; end if;
  if p_box_rating not between 1 and 5 or p_delivery_rating not between 1 and 5 then
    raise exception 'RATING MUST BE BETWEEN 1 AND 5';
  end if;

  select * into v_order
  from public.orders
  where id=p_order_id and user_id=auth.uid();

  if not found then raise exception 'ORDER NOT FOUND'; end if;
  if v_order.status<>'delivered' then raise exception 'ORDER NOT DELIVERED'; end if;
  if exists(select 1 from public.order_ratings where order_id=p_order_id) then
    raise exception 'ORDER ALREADY RATED';
  end if;

  insert into public.order_ratings(order_id,user_id,box_rating,delivery_rating,comment)
  values(p_order_id,auth.uid(),p_box_rating,p_delivery_rating,nullif(trim(coalesce(p_comment,'')),''))
  returning * into v_rating;

  return jsonb_build_object('ok',true,'rating_id',v_rating.id);
end $$;

-- Legacy physical box claiming stays available.
create or replace function public.claim_crava_box(p_box_number integer,p_claim_code text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b public.boxes;
  p public.profiles;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'reason','SIGN IN REQUIRED'); end if;
  select * into b from public.boxes where box_number=p_box_number for update;
  if not found then return jsonb_build_object('ok',false,'reason','BOX NOT FOUND'); end if;
  if b.status='not_released' then return jsonb_build_object('ok',false,'reason','THIS BOX HAS NOT BEEN ACTIVATED'); end if;
  if b.status='claimed' then return jsonb_build_object('ok',false,'reason','THIS BOX WAS ALREADY CLAIMED'); end if;
  if crypt(upper(trim(p_claim_code)),b.claim_code_hash)<>b.claim_code_hash then
    return jsonb_build_object('ok',false,'reason','INVALID PRIVATE CLAIM CODE');
  end if;

  update public.boxes set status='claimed',claimed_by=auth.uid(),claimed_at=now() where id=b.id;
  update public.profiles set box_count=box_count+1,xp=xp+100,updated_at=now() where id=auth.uid() returning * into p;
  insert into public.user_badges(user_id,badge_key) values(auth.uid(),'first_box') on conflict do nothing;
  if p.box_count>=3 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_3') on conflict do nothing; end if;
  if p.box_count>=10 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_10') on conflict do nothing; end if;
  if p.box_count>=25 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_25') on conflict do nothing; end if;
  if p.box_count>=50 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_50') on conflict do nothing; end if;
  if b.rarity in('golden','rare') then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'rare_box') on conflict do nothing; end if;

  return jsonb_build_object('ok',true,'box_id',b.id,'box_count',p.box_count,'xp',p.xp,'rarity',b.rarity);
end $$;

-- =========================================================
-- 6) Admin functions
-- =========================================================

create or replace function public.admin_store_stats()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
select case when public.is_current_user_admin() then jsonb_build_object(
  'orders_today',(select count(*) from public.orders where created_at::date=current_date),
  'new_orders',(select count(*) from public.orders where status='new'),
  'active_orders',(select count(*) from public.orders where status in('confirmed','preparing','out_for_delivery')),
  'delivered_orders',(select count(*) from public.orders where status='delivered'),
  'sales_today',(select coalesce(sum(total),0) from public.orders where status='delivered' and delivered_at::date=current_date),
  'sales_total',(select coalesce(sum(total),0) from public.orders where status='delivered'),
  'average_order',(select coalesce(avg(total),0) from public.orders where status='delivered'),
  'total_customers',(select count(*) from public.profiles where is_admin=false),
  'total_ratings',(select count(*) from public.order_ratings)
) else null end
$$;

create or replace function public.admin_rating_stats()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
select case when public.is_current_user_admin() then jsonb_build_object(
  'average_box',coalesce((select round(avg(box_rating)::numeric,2) from public.order_ratings),0),
  'average_delivery',coalesce((select round(avg(delivery_rating)::numeric,2) from public.order_ratings),0),
  'total_ratings',(select count(*) from public.order_ratings),
  'five_star_percentage',coalesce((select round(100.0*count(*) filter(where box_rating=5)/nullif(count(*),0),1) from public.order_ratings),0)
) else null end
$$;

create or replace function public.admin_update_order_status(
  p_order_id uuid,
  p_status text,
  p_admin_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders;
  v_ref public.referrals;
  v_new_balance integer;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  if p_status not in('new','confirmed','preparing','out_for_delivery','delivered','cancelled') then
    raise exception 'INVALID STATUS';
  end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'ORDER NOT FOUND'; end if;
  if v_order.status='cancelled' and p_status<>'cancelled' then
    raise exception 'CANCELLED ORDER IS FINAL';
  end if;

  update public.orders set
    status=p_status,
    admin_note=coalesce(nullif(trim(coalesce(p_admin_note,'')),''),admin_note),
    delivered_at=case when p_status='delivered' then coalesce(delivered_at,now()) else delivered_at end,
    cancelled_at=case when p_status='cancelled' then coalesce(cancelled_at,now()) else cancelled_at end,
    updated_at=now()
  where id=p_order_id
  returning * into v_order;

  -- Refund redeemed points exactly once when an order is cancelled.
  if p_status='cancelled' and v_order.points_used>0 and v_order.points_refunded_at is null then
    update public.profiles
    set points=points+v_order.points_used,updated_at=now()
    where id=v_order.user_id
    returning points into v_new_balance;

    insert into public.points_ledger(user_id,order_id,points,reason,transaction_key)
    values(v_order.user_id,v_order.id,v_order.points_used,'إرجاع نقاط الطلب الملغي #' || lpad(v_order.order_number::text,6,'0'),'order-refund-' || v_order.id::text)
    on conflict(transaction_key) do nothing;

    update public.orders
    set points_refunded_at=now(),points_balance_after=v_new_balance,updated_at=now()
    where id=v_order.id
    returning * into v_order;
  end if;

  -- Reward the inviter only once, and only after delivery.
  if p_status='delivered' then
    select * into v_ref
    from public.referrals
    where qualifying_order_id=v_order.id and reward_status='pending'
    for update;

    if found then
      update public.profiles set xp=xp+v_ref.reward_xp,updated_at=now() where id=v_ref.inviter_id;
      update public.referrals set reward_status='rewarded',rewarded_at=now(),updated_at=now() where id=v_ref.id;
      update public.orders set referral_rewarded_at=now(),updated_at=now() where id=v_order.id returning * into v_order;
    end if;
  elsif p_status='cancelled' then
    update public.referrals
    set reward_status='cancelled',updated_at=now()
    where qualifying_order_id=v_order.id and reward_status='pending';
  end if;

  return jsonb_build_object(
    'ok',true,
    'order_id',v_order.id,
    'order_number',v_order.order_number,
    'status',v_order.status,
    'points_refunded',v_order.points_refunded_at is not null,
    'referral_rewarded',v_order.referral_rewarded_at is not null
  );
end $$;

create or replace function public.admin_save_box_size(
  p_code text,
  p_price numeric,
  p_is_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v public.box_sizes;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  if upper(trim(p_code)) not in('S','M','L','XL') then raise exception 'INVALID BOX SIZE'; end if;
  if p_price is null or p_price<0 then raise exception 'INVALID PRICE'; end if;

  update public.box_sizes
  set price=round(p_price,3),is_active=coalesce(p_is_active,true),updated_at=now()
  where code=upper(trim(p_code))
  returning * into v;

  return jsonb_build_object('ok',true,'code',v.code,'price',v.price,'is_active',v.is_active);
end $$;

create or replace function public.admin_adjust_points(
  p_user_id uuid,
  p_points integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_balance integer;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  if p_points=0 then raise exception 'POINTS CANNOT BE ZERO'; end if;
  if char_length(trim(coalesce(p_reason,'')))<3 then raise exception 'REASON REQUIRED'; end if;

  update public.profiles
  set points=points+p_points,updated_at=now()
  where id=p_user_id and points+p_points>=0
  returning points into v_balance;

  if not found then raise exception 'USER NOT FOUND OR NEGATIVE BALANCE'; end if;

  insert into public.points_ledger(user_id,points,reason,transaction_key)
  values(p_user_id,p_points,trim(p_reason),'admin-' || gen_random_uuid()::text);

  return jsonb_build_object('ok',true,'points_balance',v_balance);
end $$;

create or replace function public.admin_activate_box_range(p_from integer,p_to integer,p_rarity text default 'standard')
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare c integer;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  if p_from<1 or p_to<p_from or p_to-p_from>5000 then raise exception 'INVALID RANGE'; end if;
  if p_rarity not in('standard','golden','rare') then raise exception 'INVALID RARITY'; end if;
  update public.boxes set status='active',rarity=p_rarity,activated_at=now()
  where box_number between p_from and p_to and status='not_released';
  get diagnostics c=row_count;
  return jsonb_build_object('activated',c);
end $$;

create or replace function public.admin_get_box(p_box_number integer)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare b public.boxes;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  select * into b from public.boxes where box_number=p_box_number;
  if not found then return jsonb_build_object('ok',false,'reason','BOX NOT FOUND'); end if;
  return (to_jsonb(b)-'claim_code_hash') || jsonb_build_object('ok',true);
end $$;

create or replace function public.admin_link_order_box(
  p_order_id uuid,
  p_box_number integer,
  p_rarity text default 'standard'
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare b public.boxes; o public.orders;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  if p_rarity not in('standard','golden','rare') then raise exception 'INVALID RARITY'; end if;

  select * into o from public.orders where id=p_order_id;
  if not found then raise exception 'ORDER NOT FOUND'; end if;
  select * into b from public.boxes where box_number=p_box_number for update;
  if not found then raise exception 'BOX NOT FOUND'; end if;
  if b.order_id is not null and b.order_id<>p_order_id then raise exception 'BOX ALREADY LINKED'; end if;

  update public.boxes
  set order_id=p_order_id,rarity=p_rarity,status=case when status='not_released' then 'active' else status end,
      activated_at=coalesce(activated_at,now())
  where id=b.id
  returning * into b;

  return jsonb_build_object('ok',true,'order_number',o.order_number,'box_number',b.box_number,'status',b.status);
end $$;

-- Optional helper: generates only missing physical boxes and returns their raw codes once.
create or replace function public.admin_generate_boxes(p_from integer,p_to integer)
returns table(box_number integer,claim_code text)
language plpgsql
security definer
set search_path=public
as $$
declare i integer; v_code text;
begin
  if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
  if p_from<1 or p_to<p_from or p_to-p_from>1000 then raise exception 'INVALID RANGE'; end if;

  for i in p_from..p_to loop
    if not exists(select 1 from public.boxes where public.boxes.box_number=i) then
      v_code:=upper(substr(encode(gen_random_bytes(8),'hex'),1,8));
      insert into public.boxes(box_number,claim_code_hash) values(i,crypt(v_code,gen_salt('bf')));
      box_number:=i;
      claim_code:=v_code;
      return next;
    end if;
  end loop;
end $$;

-- =========================================================
-- 7) RLS policies and grants
-- =========================================================

alter table public.profiles enable row level security;
alter table public.boxes enable row level security;
alter table public.ratings enable row level security;
alter table public.user_badges enable row level security;
alter table public.box_sizes enable row level security;
alter table public.flavor_options enable row level security;
alter table public.delivery_areas enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.points_ledger enable row level security;
alter table public.referrals enable row level security;
alter table public.order_ratings enable row level security;

-- Drop policies by known names so the file can be rerun.
drop policy if exists "profile self read" on public.profiles;
drop policy if exists "profiles read own or admin" on public.profiles;
drop policy if exists "boxes owner read" on public.boxes;
drop policy if exists "admin boxes all" on public.boxes;
drop policy if exists "ratings self read" on public.ratings;
drop policy if exists "badges self read" on public.user_badges;
drop policy if exists "public box sizes read" on public.box_sizes;
drop policy if exists "public flavors read" on public.flavor_options;
drop policy if exists "public delivery areas read" on public.delivery_areas;
drop policy if exists "orders read own or admin" on public.orders;
drop policy if exists "order items read own or admin" on public.order_items;
drop policy if exists "points ledger read own or admin" on public.points_ledger;
drop policy if exists "referrals read involved or admin" on public.referrals;
drop policy if exists "order ratings read own or admin" on public.order_ratings;

create policy "profiles read own or admin" on public.profiles
for select using(id=auth.uid() or public.is_current_user_admin());

create policy "boxes owner read" on public.boxes
for select using(claimed_by=auth.uid() or public.is_current_user_admin());

create policy "admin boxes all" on public.boxes
for all using(public.is_current_user_admin()) with check(public.is_current_user_admin());

create policy "ratings self read" on public.ratings
for select using(user_id=auth.uid() or public.is_current_user_admin());

create policy "badges self read" on public.user_badges
for select using(user_id=auth.uid() or public.is_current_user_admin());

create policy "public box sizes read" on public.box_sizes
for select using(is_active=true or public.is_current_user_admin());

create policy "public flavors read" on public.flavor_options
for select using(is_active=true or public.is_current_user_admin());

create policy "public delivery areas read" on public.delivery_areas
for select using(is_active=true or public.is_current_user_admin());

create policy "orders read own or admin" on public.orders
for select using(user_id=auth.uid() or public.is_current_user_admin());

create policy "order items read own or admin" on public.order_items
for select using(
  exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_current_user_admin()))
);

create policy "points ledger read own or admin" on public.points_ledger
for select using(user_id=auth.uid() or public.is_current_user_admin());

create policy "referrals read involved or admin" on public.referrals
for select using(inviter_id=auth.uid() or referred_user_id=auth.uid() or public.is_current_user_admin());

create policy "order ratings read own or admin" on public.order_ratings
for select using(user_id=auth.uid() or public.is_current_user_admin());

-- Public catalogue reads.
grant select on public.box_sizes,public.flavor_options,public.delivery_areas to anon,authenticated;

-- Customer reads are filtered by RLS.
grant select on public.profiles,public.orders,public.order_items,public.points_ledger,public.referrals,public.order_ratings,public.boxes,public.user_badges to authenticated;

-- Admin reads are also filtered by the admin-aware RLS policies.
grant select on public.ratings to authenticated;

grant execute on function public.is_current_user_admin() to authenticated;
grant execute on function public.create_crava_order(text,text,text,text,text,text,text,text,text,jsonb,jsonb,integer,text) to authenticated;
grant execute on function public.submit_order_rating(uuid,integer,integer,text) to authenticated;
grant execute on function public.claim_crava_box(integer,text) to authenticated;
grant execute on function public.admin_store_stats() to authenticated;
grant execute on function public.admin_rating_stats() to authenticated;
grant execute on function public.admin_update_order_status(uuid,text,text) to authenticated;
grant execute on function public.admin_save_box_size(text,numeric,boolean) to authenticated;
grant execute on function public.admin_adjust_points(uuid,integer,text) to authenticated;
grant execute on function public.admin_activate_box_range(integer,integer,text) to authenticated;
grant execute on function public.admin_get_box(integer) to authenticated;
grant execute on function public.admin_link_order_box(uuid,integer,text) to authenticated;
grant execute on function public.admin_generate_boxes(integer,integer) to authenticated;

-- Public leaderboard remains compatible with V8.
create or replace view public.leaderboard_public as
select display_name,xp,member_number
from public.profiles
where box_count>0
order by xp desc
limit 100;

grant select on public.leaderboard_public to anon,authenticated;

-- After creating your own account, replace the email and run this once:
-- update public.profiles set is_admin=true
-- where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL@example.com');

-- Ask PostgREST to refresh its schema cache immediately.
notify pgrst, 'reload schema';
