-- CRAVA V8 — Supabase setup
-- Run this entire file once inside Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Member',
  member_number bigint generated by default as identity unique,
  xp integer not null default 0,
  box_count integer not null default 0,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.boxes(
  id uuid primary key default gen_random_uuid(),
  box_number integer unique not null check(box_number > 0),
  claim_code_hash text not null,
  status text not null default 'not_released' check(status in('not_released','active','claimed')),
  rarity text not null default 'standard' check(rarity in('standard','golden','rare')),
  activated_at timestamptz,
  claimed_at timestamptz,
  claimed_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.ratings(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  box_id uuid not null references public.boxes(id) on delete cascade,
  product_id text not null,
  rating integer not null check(rating between 1 and 5),
  note text,
  created_at timestamptz not null default now(),
  unique(box_id,product_id)
);

create table if not exists public.user_badges(
  user_id uuid references auth.users(id) on delete cascade,
  badge_key text not null,
  earned_at timestamptz not null default now(),
  primary key(user_id,badge_key)
);

alter table public.profiles enable row level security;
alter table public.boxes enable row level security;
alter table public.ratings enable row level security;
alter table public.user_badges enable row level security;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name','Member')); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_current_user_admin() returns boolean language sql stable security definer set search_path=public as $$
select coalesce((select is_admin from public.profiles where id=auth.uid()),false) $$;

create policy "profile self read" on public.profiles for select using(id=auth.uid() or public.is_current_user_admin());
create policy "ratings self read" on public.ratings for select using(user_id=auth.uid() or public.is_current_user_admin());
create policy "badges self read" on public.user_badges for select using(user_id=auth.uid() or public.is_current_user_admin());
create policy "boxes owner read" on public.boxes for select using(claimed_by=auth.uid() or public.is_current_user_admin());
create policy "admin boxes all" on public.boxes for all using(public.is_current_user_admin()) with check(public.is_current_user_admin());

create or replace function public.claim_crava_box(p_box_number integer,p_claim_code text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare b public.boxes; p public.profiles;
begin
 if auth.uid() is null then return jsonb_build_object('ok',false,'reason','SIGN IN REQUIRED'); end if;
 select * into b from public.boxes where box_number=p_box_number for update;
 if not found then return jsonb_build_object('ok',false,'reason','BOX NOT FOUND'); end if;
 if b.status='not_released' then return jsonb_build_object('ok',false,'reason','THIS BOX HAS NOT BEEN ACTIVATED'); end if;
 if b.status='claimed' then return jsonb_build_object('ok',false,'reason','THIS BOX WAS ALREADY CLAIMED'); end if;
 if crypt(upper(trim(p_claim_code)),b.claim_code_hash)<>b.claim_code_hash then return jsonb_build_object('ok',false,'reason','INVALID PRIVATE CLAIM CODE'); end if;
 update public.boxes set status='claimed',claimed_by=auth.uid(),claimed_at=now() where id=b.id;
 update public.profiles set box_count=box_count+1,xp=xp+100 where id=auth.uid() returning * into p;
 insert into public.user_badges(user_id,badge_key) values(auth.uid(),'first_box') on conflict do nothing;
 if p.box_count>=10 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_10') on conflict do nothing; end if;
 if p.box_count>=25 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_25') on conflict do nothing; end if;
 if p.box_count>=50 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_50') on conflict do nothing; end if;
 if p.box_count>=3 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'collector_3') on conflict do nothing; end if;
 if b.rarity in('golden','rare') then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'rare_box') on conflict do nothing; end if;
 return jsonb_build_object('ok',true,'box_id',b.id,'box_count',p.box_count,'xp',p.xp,'rarity',b.rarity);
end $$;

create or replace function public.submit_crava_ratings(p_box_id uuid,p_ratings jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare item jsonb; p public.profiles; rare boolean;
begin
 if not exists(select 1 from public.boxes where id=p_box_id and claimed_by=auth.uid() and status='claimed') then return jsonb_build_object('ok',false,'reason','BOX OWNERSHIP NOT VERIFIED'); end if;
 if exists(select 1 from public.ratings where box_id=p_box_id) then return jsonb_build_object('ok',false,'reason','THIS BOX WAS ALREADY RATED'); end if;
 for item in select * from jsonb_array_elements(p_ratings) loop
   insert into public.ratings(user_id,box_id,product_id,rating,note) values(auth.uid(),p_box_id,item->>'product_id',(item->>'rating')::int,nullif(item->>'note',''));
 end loop;
 update public.profiles set xp=xp+50 where id=auth.uid() returning * into p;
 insert into public.user_badges(user_id,badge_key) values(auth.uid(),'first_rating') on conflict do nothing;
 if exists(select 1 from public.ratings where user_id=auth.uid() and product_id='chocolate_twist') then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'chocolate_taster') on conflict do nothing; end if;
 if exists(select 1 from public.ratings where user_id=auth.uid() and product_id='strawberry_twist') then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'strawberry_taster') on conflict do nothing; end if;
 if exists(select 1 from public.ratings where user_id=auth.uid() and product_id='custard_twist') then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'custard_taster') on conflict do nothing; end if;
 if exists(select 1 from public.ratings where user_id=auth.uid() and product_id='lotus_twist') then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'lotus_taster') on conflict do nothing; end if;
 if (select count(*) from public.ratings where user_id=auth.uid())>=10 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'ratings_10') on conflict do nothing; end if;
 if (select count(*) from public.ratings where user_id=auth.uid())>=25 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'ratings_25') on conflict do nothing; end if;
 if (select count(*) from public.ratings where user_id=auth.uid())>=50 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'ratings_50') on conflict do nothing; end if;
 if (select count(distinct product_id) from public.ratings where user_id=auth.uid() and product_id in ('chocolate_twist','strawberry_twist','custard_twist','lotus_twist'))=4 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'passport_complete') on conflict do nothing; end if;
 if p.xp>=1200 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'level_elite') on conflict do nothing; end if;
 if p.xp>=4000 then insert into public.user_badges(user_id,badge_key) values(auth.uid(),'crava_icon') on conflict do nothing; end if;
 select rarity in('golden','rare') into rare from public.boxes where id=p_box_id;
 return jsonb_build_object('ok',true,'xp',p.xp,'rare_reward',rare);
end $$;

create or replace view public.leaderboard_public as
select display_name,xp,member_number from public.profiles where box_count>0 order by xp desc limit 100;

grant select on public.leaderboard_public to anon,authenticated;
grant execute on function public.claim_crava_box(integer,text) to authenticated;
grant execute on function public.submit_crava_ratings(uuid,jsonb) to authenticated;
grant execute on function public.is_current_user_admin() to authenticated;

create or replace function public.admin_activate_box_range(p_from integer,p_to integer,p_rarity text default 'standard')
returns jsonb language plpgsql security definer set search_path=public as $$
declare c integer;
begin
 if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
 if p_from<1 or p_to<p_from or p_to-p_from>5000 then raise exception 'INVALID RANGE'; end if;
 update public.boxes set status='active',rarity=p_rarity,activated_at=now() where box_number between p_from and p_to and status='not_released';
 get diagnostics c=row_count; return jsonb_build_object('activated',c);
end $$;

create or replace function public.admin_get_box(p_box_number integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare b public.boxes;
begin if not public.is_current_user_admin() then raise exception 'ACCESS DENIED'; end if;
select * into b from public.boxes where box_number=p_box_number;
return to_jsonb(b)-'claim_code_hash'; end $$;

create or replace function public.admin_dashboard_stats()
returns jsonb language sql security definer set search_path=public as $$
select case when public.is_current_user_admin() then jsonb_build_object(
'total_boxes',(select count(*) from public.boxes),
'active_boxes',(select count(*) from public.boxes where status='active'),
'claimed_boxes',(select count(*) from public.boxes where status='claimed'),
'members',(select count(*) from public.profiles),
'ratings',(select count(*) from public.ratings)
) else null end $$;

grant execute on function public.admin_activate_box_range(integer,integer,text) to authenticated;
grant execute on function public.admin_get_box(integer) to authenticated;
grant execute on function public.admin_dashboard_stats() to authenticated;

-- Generate your first 1000 boxes with random private codes.
-- IMPORTANT: Run this block once, then immediately export the result as CSV.
create temporary table if not exists generated_crava_codes(box_number int,claim_code text);
truncate generated_crava_codes;
do $$
declare i int; code text;
begin
 for i in 1..1000 loop
   code:=upper(substr(encode(gen_random_bytes(8),'hex'),1,8));
   insert into public.boxes(box_number,claim_code_hash) values(i,crypt(code,gen_salt('bf'))) on conflict(box_number) do nothing;
   insert into generated_crava_codes values(i,code);
 end loop;
end $$;
select box_number,claim_code from generated_crava_codes order by box_number;

-- After you create your own account, replace the email below and run once:
-- update public.profiles set is_admin=true
-- where id=(select id from auth.users where email='YOUR_ADMIN_EMAIL@example.com');
